### PR TITLE
Ny time complete

### PR DESCRIPTION
**Pull request by codesalley**

### CODE REVIEW

**Comment by mimipeshy** [comment]
### STATUS :INVALID SUBMISSION :red_circle: :recycle: 

Hey there @juxsalley and @Bishoy-Samwel :wave: :wave: Welcome to Microverse :smile: Good job on working on this project. However, this submission will be marked as invalid because your PR is not professional.
On the description box provided, add a brief description of your project and what you achieved while working on it, Also check on linter errors and fix them before submitting another review.

Thats all :smile: , submit another review when done.

Regards
Peris Ndanu.
Feel free to slack me if you have any questions.

**Review by SpaYco — CHANGES_REQUESTED** [review]
## Invalid 🛑 

in order to validate this project:

* [ ] Pull Request has a meaningful title and a brief description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
* [ ] fix linters ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/linter_config.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/))


Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

**Review by Srjnnnn — CHANGES_REQUESTED** [review]
## Changes Required :recycle: :stop_sign: 
Hello team! Your page looks good but there are some things to be done before moving on.

- [ ] The New York Times should be a logo and a link.

- [ ] Your video is not centered and your second image is too big.

- [ ]  You can decrease the width of the writings and try to mimic the page more.

- [ ]  Please add a proper Readme for the repository.

- [ ]  There is a horizontal scroll bar on your page. Please fix this issue and make it to fit one page.

You've used mostly semantic HTML, and I can see that you are improving your positioning talents. :muscle: After making those changes please submit for a re-review.

If you have any question about the review, you can reach out to me via Slack. :100: 
_Eyüp Sercan UYGUR_

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @Bishoy-Samwel 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##

Kindly work on the suggested changes 👇.
- [ ] Use a signal image in The Theory of Inflation like [original page image](https://static01.nyt.com/newsgraphics/2014/03/18/theory-of-inflation/1ebaa1b972edda0f407fbaa0e010f6b50fb6792e/inflation-720.png).
- [ ] Add `Editor's picks` section on the righmost side. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/aside_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/))
- [ ] Please add a descriptive README.md and PR description([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
- [ ] Please add the .gitgonre file
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @Bishoy-Samwel  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your clone looks like the original page and it is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done.
#### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
### Please implement the previous reviewer's required changes:
> Use a signal image in The Theory of Inflation like original page image.
> Add Editor's picks section on the righmost side. (screenshot from Pathwright)
> Please add a descriptive README.md and PR description(screenshot from Pathwright)
> Please add the .gitgonre file
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Comment by mimipeshy** [comment]
### STATUS : CHANGES REQUIRED :red_circle: :recycle: 

Hello team @juxsalley, great job on working on this project. I liked that you have tried to implement the requested changes from the previous review, keep it up, and your project is really almost done. However, there are some changes you haven't implemented and they are required before your project is approved; I will highlight them below:

#### MANDATORY :red_circle: 

- [ ]  Add Editor's picks section on the righmost side.([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/aside_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/))
image

- [ ] Your README file is not complete. The following sections are missing:

-  Live Demo link is not working, it's broken
- Setup instructions are not clear for someone who is new to Github. For example `clone to local storage` is a vague instruction. You can write something like `git clone <repo_url>`, `cd folder_name`, `run <file.html> on your favorite browser`. 
-  Add more social accounts like Twitter or LinkedIn
- Your MIT license is broken

- [ ] On the description box provided, add a brief description of your project and what you achieved while working on it
- [ ] Add a .gitignore file. This file is used to ignore files that are not being used by your project such as .vscode. It also makes your Repo professional

That's all :smile: , Kindly ensure you work on **ALL** the feedback given before submitting another review.

Regards 
Peris Ndanu
Feel free to slack me if you have any questions and i will be glad to help.

**Comment by codesalley** [comment]
> ### STATUS : CHANGES REQUIRED 🔴 ♻️
> Hello team @juxsalley, great job on working on this project. I liked that you have tried to implement the requested changes from the previous review, keep it up, and your project is really almost done. However, there are some changes you haven't implemented and they are required before your project is approved; I will highlight them below:
> 
> #### MANDATORY 🔴
> * [ ]   Add Editor's picks section on the righmost side.([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/aside_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/))
>   image
> * [ ]  Your README file is not complete. The following sections are missing:
> * Live Demo link is not working, it's broken
> * Setup instructions are not clear for someone who is new to Github. For example `clone to local storage` is a vague instruction. You can write something like `git clone <repo_url>`, `cd folder_name`, `run <file.html> on your favorite browser`.
> * Add more social accounts like Twitter or LinkedIn
> * Your MIT license is broken
> * [ ]  On the description box provided, add a brief description of your project and what you achieved while working on it
> * [ ]  Add a .gitignore file. This file is used to ignore files that are not being used by your project such as .vscode. It also makes your Repo professional
> 
> That's all 😄 , Kindly ensure you work on **ALL** the feedback given before submitting another review.
> 
> Regards
> Peris Ndanu
> Feel free to slack me if you have any questions and i will be glad to help.

i can't find Editor's pics, just plain text

**Review by mcrd25 — APPROVED** [review]
# Changes Approved :heavy_check_mark: 

Hi @Bishoy-Samwel :wave: 


Good job with the changes! 
I think you've done enough to be approved.
The reason for this is most likely adblocker. If you remove adblocker from running on the page you should see it. Hope that helps in future.. :slightly_smiling_face: 


***If you have any questions, now or in the future, do not hesitate to contact me on social media, email or on slack and I will be glad to chat with you.***

If you liked my review, consider upskilling me on LinkedIn. And please do connect. [My LinkedIn](https://www.linkedin.com/in/mayadouglas/)


*Happy coding 😄,*
**[--Maya Douglas](mayacdouglas.com)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

**Pull request merged**
